on: [push, pull_request]

jobs:
  black-test:
    name: Black Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jpetrucciani/black-check@master
        with:
          path: "backend/"